### ISSUE TITLE
Build error on Flutter version 1.17.0

### ISSUE THREAD

**Issue by forestsoftjpdev** [alann-maulana/flutter_hud#6]
Compiler message:
../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hud-0.2.1/lib/src/popup_hud.dart:57:31: Error: This expression has type 'void' and can't be used.
  bool dismiss() => Navigator.pop(context);
                              ^

Compiler message:
../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hud-0.2.1/lib/src/popup_hud.dart:57:31: Error: This expression has type 'void' and can't be used.
  bool dismiss() => Navigator.pop(context);

**Comment by zakaio** [comment]
Hi, are there any updates on this?

**Comment by forestsoftjpdev** [comment]
Probably, Fixed this commit 
https://github.com/eyro-labs/flutter_hud/commit/0d5ed29fc2aa97dff2863ab824dba48264048c6a


Do you have an update release planned?
